-- Users table
CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL
);
GO

-- MoodEntries table
CREATE TABLE MoodEntries (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Mood NVARCHAR(50) NOT NULL,
    Notes NVARCHAR(MAX) NULL,
    Date DATETIME NOT NULL DEFAULT GETUTCDATE(),
    UserId INT NOT NULL,
    CONSTRAINT FK_MoodEntries_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
GO
